### ISSUE TITLE
Music 1 & 2 

### ISSUE THREAD

**Issue by VulcanGDL** [GDLDiscord/server#11]
Music 1 & 2 to run off the same playlist as DJ-Justine

Then there is no need to worry about updating the playlist and having bad songs etc

**Comment by LordBonzi** [comment]
Post the Playlist Dump link ``[prefix]pldump [playlist link]``
That should spew out a txt file, grab its link

#__Note__
If the playlist is updated on YouTube, we (@LordBonzi & @VulcanGDL) will have to manually intervene to update the playlist on the bot's autoplayist file

**Comment by VulcanGDL** [comment]
[playlist (3).txt](https://github.com/GDLDiscord/server/files/1005005/playlist.3.txt)

**Comment by VulcanGDL** [comment]
Playing good across all 2 bots
