### ISSUE TITLE
Migrate gdlcommunity.ga's CNAME record to github.io

### ISSUE THREAD

**Issue by LordBonzi** [GDLDiscord/server#12]
__**Instructions to move from Freenom GoSite to the new website**__

1. Open freenom
2. Find the domain
3. Disable GoSite
4. Go to the domain settings
5. Go to freenom DNS Management
6. Add a CNAME where the 1st block is blank and the Drop down menu says CNAME, the number is left as it is and the last box should be set to ``gdldiscord.github.io``

**Comment by VulcanGDL** [comment]
Step 6 fior DNS Management page says: "Zone is not active yet."

**Comment by LordBonzi** [comment]
Upload a screenshot thanks

**Comment by LordBonzi** [comment]
Actually, try instead of a CNAME, Use a A record, set the address to ``192.30.252.153`` (Github's webhosting IP) and it *should™* work

**Comment by LordBonzi** [comment]
Website is now migrated

**Comment by VulcanGDL** [comment]
Thanks
