### ISSUE TITLE
GDL Music Bots (1 & 2)

### ISSUE THREAD

**Issue by VulcanGDL** [GDLDiscord/server#2]
GDL Music 1 bot to be used by all users.

GDL Music 1 & 2 prefix change - < and >

**Comment by JWGDL** [comment]
Upon with this we need allow the bot commands to be used in #bot_commands as it only works in the #music_bot1_cmds chat (Just trying to point out something incase that it is forgotten)

**Comment by LordBonzi** [comment]
I'll change the prefixes soon, mans gotta life to live tho

**Comment by LordBonzi** [comment]
Prefixes Have Been Changed

music 2 <

music 1 >
