### ISSUE TITLE
Suggestions - RussianRoulette

### ISSUE THREAD

**Issue by TheRockettek** [GDLDiscord/server#6]
commands:
rr spin - Spin the barrel
rr fire - Shoot

variables:
barrelCount - Holds the number of the barrel

rr spin:
when they do the command it sets the barrelCount randomly from 1 to 6 and you could make it say in bold "You spin the barrel, not knowing where the bullet is..."

rr fire:
when they do the command you cold make it say in bold "You hold the gun next to your head. Trembling, you put the gun to your head and press the trigger..."

if barrelCount == 1 then
say in bold "Bang! The impact of the gun shot damaged your skull and you died instantly right there."
else
say in bold "Click! Nothing came out. You gave a sigh of relief"

once every time someone uses fire, barrelCount will increment by one and once its at 6 and increments back to 1

**Comment by VulcanGDL** [comment]
I think this can be added, thanks for sharing

**Comment by VulcanGDL** [comment]
Added thanks for the suggestion!
