### ISSUE TITLE
Suggestions - Yomomma

### ISSUE THREAD

**Issue by TheRockettek** [GDLDiscord/server#7]
commands:
yomomma - Litteraly says just a yomomma joke

yomomma:

If you http get "http://api.yomomma.info/" you will get json containing a joke with the joke being called joke. You could either decode it or just simply gsub the " {"joke":" " and " "} " and then just tell it to the user
:D

**Comment by VulcanGDL** [comment]
Started writing this, will try to finish over the weekend!

**Comment by VulcanGDL** [comment]
Pretty much got the main thing done, slight problem with the API that I used. Will look into to this more possibly tomorrow when I get some free time :smile:

**Comment by VulcanGDL** [comment]
Done 👌 

do: `gdl-yomamma @user#0000`
