### ISSUE TITLE
Command issues

### ISSUE THREAD

**Issue by TheRockettek** [GDLDiscord/server#9]
gdl-update
  When setting text with gdl-update about, there will be a space missing at the end
  "You have updated your About Me tomissing space"
gdl-team
  The gdl-team new command doesn't change based on the command prefix
  "Under construction. use !adventure embark <team_name> instead"
gdl-allin
  This command wont work at all.
  "Error in command 'allin' - KeyError: '143090142360371200'"
gdl-coin
  If the bit ammount isnt 10 it wont work. Why not just ignore the bid ammount and set it to 10 every time
gdl-coin,gdl-hilo,gdl-war
  Same thing as coin but instead the bid has to be 20
gdl-war
  The cooldown is active even when the command isnt successfuly executed such as not putting 20 as the bid
gdl-chatterbot
  Freezes the entire bot for 30seconds+. Caused by http delay (?). GDL cannot use async so if the command is frozen no other commands can be used. Affects other servers if another one freezes gdl (?)
gdl-customcommands
  Does nothing.
gdl-lsgcom
  The invite link to the discord server is expired
gdl-gaming
  The message needs to be more clear as it doesnt show its a different command. Should use the prefix on it for better understanding of a different command.
  "Type help gaming for info."
gdl-git
  You should use the actually prefix instead of [p] 👍 
  ..."Use [p]help git for more info."...
gdl-info
  Still broken.
  "Error in command 'info' - NameError: name 'dpy_repo' is not defined"
gdl-welcomer
  Anyone can use the commands in this meaning that anyone can edit the welcome text
  ![image](https://cloud.githubusercontent.com/assets/17106916/25865848/520b9026-34ec-11e7-86ec-313f7d5a8fb6.png)

**Comment by VulcanGDL** [comment]
the welcomer cog is my main focus.

The welcomer cog isn't even made by me it was a cog I added for a better welcome message.

Although I can probally add a check if owner  to it. Although I will have to take a look at this first.

Please could you add the other problems seperatly so we can track them easier thanks

**Comment by VulcanGDL** [comment]
Im going to close this. Ive noted the main things. Please post each issue one at a time as it is much easier to read and keep track of whats been done and what needs to be done - Thanks
